### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by kuraydev** [sivantha96/react-native-styled-datepicker#1]
Hello @sivantha96 
I would like to work with this library but I could not install it.

FYI
<img width="588" alt="CleanShot 2022-06-06 at 00 17 30@2x" src="https://user-images.githubusercontent.com/6813862/172070984-827e6b35-5818-48f4-a1b6-250de5a7305e.png">

**Comment by sivantha96** [comment]
try with `npm install react-native-styled-datepicker --save --legacy-peer-deps`
