### ISSUE TITLE
Can't change the color of arrow

### ISSUE THREAD

**Issue by naimur978** [sivantha96/react-native-styled-datepicker#2]
There're 2 props for the arrow (around month and year)
1. Arrow Wrapper Styles
2. Arrow Styles

But unfortunately, I can't change the colour of the arrow with any of these props!

Am I missing the math?

**Comment by FaysalBsata** [comment]
> There're 2 props for the arrow (around month and year)
> 
> 1. Arrow Wrapper Styles
> 2. Arrow Styles
> 
> But unfortunately, I can't change the colour of the arrow with any of these props!
> 
> Am I missing the math?

arrowStyles={{ tintColor: 'white', }}
